[package]
name = "libronoa_lexer"
version = "0.0.0"
authors = ["Nattakit Hosapsin <nattakit@hosapsin.com>"]
license = "LGPL-3.0-or-later"
edition = "2018"

[lib]
name = "libronoa_lexer"
path = "lib.rs"

[dependencies]
