[package]
name = "ronoa"
version = "0.0.1"
authors = ["Nattakit Hosapsin <nattakit@hosapsin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
