[package]
name = "ronoa"
version = "0.0.0"
authors = ["Nattakit Hosapsin <nattakit@hosapsin.com>"]
edition = "2018"

[[bin]]
name = "ronoa"
path = "ronoa.rs"

[dependencies]
libronoa = { path ="../libronoa" }

